In [ ]:
print('ezz')

ezz


In [ ]:
print(10)

10


In [ ]:
print('ezz',end='')#هنا مش هيعمل مسافه
print('afify')

ezzafify


In [ ]:
print('ezz',end='   ')#هنا هيعمل مسافه بين الكلمتين
print('afify')

ezz   afify


In [ ]:
print(3+5j)

(3+5j)


In [ ]:
x=10
if x==10: #هنا لازم اتنين يساوي علشان يطبع
     print(10)
else:
     print(4) 

10


In [ ]:
x=10
print(x)

10


In [ ]:
a=int(4.5)
print(a)

4


In [ ]:
v=float(1.4)
print(v)

1.4


In [ ]:
x=10.76
print(int(x))
#1=544#هنا بقا مينفعشي اسجل برقم اي حاجه
#print(1)

10


In [ ]:
x=2
x=3
x=5
print(x)#هنا بقا بياخد اخر X

5


In [ ]:
x=0
print(bool(x))
print(bool(7))#اي حاجه ب بصفر =FALSE

False
True


In [ ]:
a=b=c=6
print(a)

6


In [ ]:
a,b,c=1,2,3 #هنا بيشتغل بالترتيب
print(b)

2


In [ ]:
print(complex(10,2))#هنا عرف التانيه الا complex

(10+2j)


In [ ]:
str='ezzmohamed'
print(str)

ezzmohamed


In [ ]:
e='ezzafify'
e[7] #هنا بيبدا من الصفر 
print(e[7])

y


In [ ]:
r='ezz'
r[-1] #هنا هيطبع اول حرف شمال لان ال-1 بيبدا من النهايه
print(r[-1])

z


In [ ]:
#عاوز احدد الاسم كله واطبعه اعمل اي 
t='ezzmohamed'
t[0:10] # هنا طبع الاسم كله علشان انا عملت ده
print(t[0:10])

ezzmohamed


In [ ]:
#فيه طريقه تانيه بس انا بقوله هنا ابدا من البدايه 
p='alaa'
p[:4] #هنا بقوله ابدا من البدايه
print(p[:4])

alaa


In [ ]:
u='ahmedezzmohamed'
u[0:15:2] #هنا الindex 3 يبقي نطلع 2 
print(u[0:15:2])
#هنا بشيل الحرف الا مش عاوزه

amdzmhmd


In [ ]:
#شكل الstep بطريقه تانيه
r='ezzezzezz'
r[::3] #هنا بقوله ابدا من الاول الي الاخر والstep=4
print(r[::3])

eee


In [ ]:
o='123456789'
o[::-2] #هنا هيبدا من -1 والstep=-1
print(o[::-2])

97531


In [ ]:
o='ezzmohamedaliafify'
o[-1:-18:-5] #هنا بشتغل عادي بس من العكس 
print(o[-1:-18:-5])

yimz


In [ ]:
a='ezz'
b='afify'
print(a+b)
print(a*2)

ezzafify
ezzezz


In [ ]:
x='ezz'
print(x.upper()) #بيخلي الحروف كبيره

EZZ


In [ ]:
y='EZZ'
print(y.lower()) #بيخلي الحروف صغيره

ezz


In [ ]:
x='ezzaliafify'
y=x.find('y')
print(y)

10


In [ ]:
print('🩶🖤'*20)#هنا لو عاوز اكرر حاجه كذا مره

🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤🩶🖤


In [ ]:
input('name')


'ezz'

In [ ]:
print('ezz{} afify{}'.format(10,20)) #هنا بيخلي الارقام جنب الاسماء 

ezz10 afify20


In [ ]:

print('ezz\'afify') #هنا بيطبع الاتنين ججنب بعض وبينهم 

ezz'afify


In [ ]:

print('ezz\\afify') #|هنا بطبع \بس بين الاسمين 

ezz\afify


In [ ]:
print('ezz\nafify') #هنا الاسم الاول ف سطر والاسم التاني ف سطر تحت بعض لو مفيش مسافه

ezz
afify


In [ ]:
print('ezz\tezz')#هنا بيعمل مسافه بين الكلمتين 

ezz	ezz


In [ ]:
print('ezz\bez\bz')#هنا بيمسح الحرف الا قبله

ezez


In [ ]:
x=10
y=5
print(x+y,x-y,x*y,x/y)#هنا عمليات الحسابيه

15 5 50 2.0


In [ ]:
x=10
y=20
if x>y  : # بقا نحط اي حاجه من دول <,>,=,>=,<=,!= 
          print('yes')
else:
          print('no') 

no


In [ ]:
print(2==2 and 3==3)#هنا هيطبع صح لان الجانبين صح 
print(2==2 or 2==3) #هنا هيطبع صح ف حالة واحده بس الا صح
print(not(2==2 and 4==4)) #هنا الجانبين صح بس علشان حاطط notهيعكس 


True
True
False


In [ ]:
x=20
if x<=20 :   #ده امر if لما يكون لوحده 
    print('hello')

hello


In [ ]:
x=10
if x>10 :
    print('ture')
else:                    #هنا استخدمة if and else 
    print('false')

false


In [ ]:
x=int(input('enter the number')) #هنا دخلت رقم من المستخدم
if x<30:
    print('small')
elif x==30:            #هنا استخدمنا elif علشان عندي تلات احتمالات 
    print('good')
else:
    print('big')

small


In [ ]:
op=input('enter the op')
x1=int(input('num1='))
x2=int(input('num2=')) 
if op=='+':
    print(x2+x1)
elif op=='-':
    print(x2-x1)
elif op=='*':
    print(x2*x1)
else:
    print(x2/x1)
 #نعمل هنا اله حاسبه

5


In [ ]:
x=10
if x==10:
    print('ture') #هنا حاجه اسمها nested يعني كذا if جوه بعض 
    if x>=10:
        print('ture2')
        # ممكن نعمل ده بطريقه تانيه 
x=10
if x==10 and x>=10 : #هنا حطيت الشرطين مع بعض ف كود
    print('ture and ture1')

ture
ture2
ture and ture1


In [ ]:
#هنا هنعمل سؤال عن الاعمار
"""Problem 1: Age Categorization
Write a function that categorizes people based on their age:
"Child" if age is less than 13
"Teenager" if age is between 13 and 19
"Adult" if age is between 20 and 64
"Senior" if age is 65 or older"""

age=int(input('enter the age'))
if age<13:
    print('child')
elif age>=13 and age<=19 :
    print('Teenager')
elif age>=20 and age<=64 :
    print('Adult')
else:
    print('Senior')

child


In [ ]:
e='ezz'
for i in e : #كده عندي loopالا هوا الاسم عدد الحروف 
    print( i) #الi عندي ده يعتبر العداد بتاعي هوا الا بيعد الحروف
# i-counter  اي حرف غير الiعادي

e
z
z


In [ ]:
e='ezz'
for u in range(len(e)) : #الطريقه ده بطبع الsequences علي نظام range من كذا الي كذا
    print( u )
print('loop finished') # هنا بيعرفني ان loop خلص

0
1
2
loop finished


In [ ]:
#طب انا لو عاوز يطبع الحرف والindex جنبه اعمل اي 
e='ezz'
for a in range(len(e)):
    print('char: ',a,'is' ,e[a]) #هنا عملت الحرف وجنبه الindex بتاعه

char:  0 is e
char:  1 is z
char:  2 is z


In [ ]:
# هنشتغل while loop بالطريقه بتاعتها بس نفس الoutput بتاع for
e='ezz'
u=0 # هنا بقوله البدايه من الصفر
while u<len(e):
    print('char: ' ,e[u] )
    u+=1    #هنا بقوله زود واحد كل مره 
print('loop finished')

char:  e
char:  z
char:  z
loop finished


In [18]:
for i in range(5):
    if i==3 :
        break
    print(i)


0
1
2


In [21]:
#match case هنا هنعرف يعني اي 
#هنعمل اله حاسبه بواسطة الmatch case
op=input('enter the op')
x=int(input('enter the x='))
y=int(input('enter the y='))
match op:
    case '+':
        print(x+y)
    case'-':
        print(x-y)
    case'*':
        print(x*y)
    case '/':
        print(x/y)
    case _ : #اخر واحده ده لو معنديش اي حاجه من الا فوق 
        print('I dont not have')

5


In [22]:
#عاوز اعمل لسته 
e=['ezz',9,'ali','alaa']
print(e[3]) #هنا كده عملت لستة وطبعت الا انا عاوزه

alaa


In [23]:
#طب دلوقتي عاوز اعمل indexing and slicing
A=[1,2,3,4,5,6]
print(A[-1])
print(A[2]) #دول بقا indexing
print(A[2:3])
print(A[:-1])#دول بقا ال slicing

6
3
[3]
[1, 2, 3, 4, 5]


In [24]:
#ممكن اشيل لسته داخل لسته
x=[1,3,2,4,5,[1,2,3]]
print(x[-1])

[1, 2, 3]


In [26]:
#ممكن اشتغل ع اللسته الا جوه اللسته 
y=[1,2,3,4,5,[9,8,7]]
print(y[-1][1])
print(y[::3]) #هنا بقوله من الاول للاخر بس index=3 
print(y[::-1])#هيبدا من الاول للاخر بس من النهايه

8
[1, 4]
[[9, 8, 7], 5, 4, 3, 2, 1]


In [27]:
#طريقه تانيه لتعريف لسته 
x=list([1,2,3,4,5,6,7])
print(x[4])


5


In [28]:
# هنا هنتكلم ع شوية خواص ف list
#append,insert
x=[1,3,4,5,6,7]
x.append(8) #append بتضيف قيمه ف نهاية اللسته
print(x)
y=[1,3,4,5,6,7]
y.insert(1,2) #insertبتضيف قيمه بس انا بحدد مكانها 
print(y)
#insert تنفع بالسالب 
z=[1,2,3,5]
z.insert(-1,4) #هنا مش بيقف عند السالب 1 بالظبط بينط بعده برقم
print(z)

[1, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5]


In [29]:
#خواص ف الlist
#remove  and  pop
e=[1,3,4,6,9,7,8]
e.remove(3) #هنا بتشيل القيمه الا جوه remove
print(e)
q=[1,7,45,3,1,4,9]
q.pop(2)#هنا بتشيل المكان الا جوه pop
print(q)

[1, 4, 6, 9, 7, 8]
[1, 7, 3, 1, 4, 9]


In [32]:
#خواص ف الlist
#sort and reverse
p=[2,8,7,6,3,1,4,5,9]
p.sort() #sortهنا عملت ترتيب ل list من الصغير للكبير 
print(p)
#طب لو عاوز من الكبير للصغير
u=[4,5,54,32,1,4,2,76,3,0]
u.sort(reverse=True) #هنا عمل sort من الكبير الي الصغير 
print(u)
s=[1,2,3,4,5,6,7,8,9]
s.reverse()#reverse هنا عملت عكس ل list
print(s)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[76, 54, 32, 5, 4, 4, 3, 2, 1, 0]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [33]:
#طب انا عاوز اعرف رقم كل حرف ف بايثون كام اعمل اي 
ord('e')

101

In [34]:
#list خواص ف ال
# clear and count and copy and index and extend
x=[1,2,3,4,5,6,7,8,90,0,4]
x.clear() #clear هنا بتمسح الlist كلها 
print(x)
#########################################################
x=[1,2,34,21,2,1,1,2,3,4,56,7,4,111,1,1,1]
x.count(1) # count هنا بتعدد الرقم متكرار كام مره 
print(x.count(1))
#########################################################
x=[1,2,3,4,5,6]
x.copy()#copy بتاخد نسخه من الاسم وتطبعه
print(x)
###########################################################
x=[1,2,3,4,5,6,7]
x.index(3)#index هنا بتعمل اي بترجع الرقم الا انا كاتبه مكنه فين 
print(x.index(3))
###########################################################
x=[1,2,3,4,5,6,7,8]
y=[8,7,6,5,4,3,2,1]
x.extend(y)#extend هنا بتعمل اني بضيف list جوه list
print(x)

[]
6
[1, 2, 3, 4, 5, 6]
2
[1, 2, 3, 4, 5, 6, 7, 8, 8, 7, 6, 5, 4, 3, 2, 1]


In [35]:
#tuple شكل 
x=1,2,3#ينفع اعمل accessing عليه 
print(x[1])

2


In [37]:
#ممكن اعمل concatenation 
x=1,2,3
y=3,4,5
z=x+y
print(z)
q=tuple([1,2,3])
w=tuple([4,5,6]) #بطريقه تانيه 
print(q+w)

(1, 2, 3, 3, 4, 5)
(1, 2, 3, 4, 5, 6)


In [40]:
#معرفة الtuple
x=1, #هنا tuple
print(type(x))

<class 'tuple'>


In [41]:
#علشان اعدل ف الtuple لازم احوله ل list الاول وبعدين اعدل وبعدين احوله تاني الي tuple
a=1,
a=list(a)
a.append(2)
a=tuple(a)
print(a)

(1, 2)


In [ ]:
#معرفة set
#طريقه 1
my_set={1,2,3,4,5,6,6,6,6,6,6,6,6,6}
print(my_set)#مش بتسمح بتكرار الارقام
#لو عاوز اعرف set فاضيه 
x=set()# هنا عرفتها انها فاضيه 
print(type(x))


{1, 2, 3, 4, 5, 6}
<class 'set'>
{1, 2, 4, 5, 6, 10}
{2, 3, 4, 5}


In [43]:
#خواص set
#add and remove
my_set={1,2,4,5,6}
my_set.add(10)#هنا بعمل اضافه 
print(my_set)
x={1,2,3,4,5}
x.remove(1)#هنا مسحت عنصر
print(x)

{1, 2, 4, 5, 6, 10}
{2, 3, 4, 5}


In [44]:
#خواص الset
#union and intersection and difference
set1={1,2,3,4,5}
set2={2,6,8,3,1}
print(set1|set2) #هنا بتحط الاتنين مع بعض مع اختلاف طبعا
######################
set3={1,2,3,4,5}
set4={3,4,5,6}
print(set3&set4)# هنا بيطلع التقاطع بينهم 
#######################
set5={1,2,3,4,5}
set6={4,5,6,7}
print(set5-set6) #معني الكلام اي الا موجود ف 1 ومش موجود ف 2
########################
x1={1,2,3,4,5,6}
x2={6,7,8,9}
x1.intersection_update(x2) #هنا بعمل اي بجيب التقاطع بينهم واطبع x1 يطلع التقاطع الجديد
print(x1)
##########################
x1={1,2,3,4,5,6}
x2={3,4,5,6,7}
x1.difference_update(x2)#هنا بردوا نفس الكلام بجيب الفرق واخزينه ف x1
print(x1)
######################################################################
x1={1,2,3,4,5,6,7,8,9}
x1.remove(6)#هنا بتمسح العنصر\لو العنصر مش موجود هتطلع ايرو
print(x1)
##############################
x={1,2,3,4,5,7,8,9,10}
x.discard(x)#هنا بقا بتمسح الرقم لو موجود\لو العنصر مش موجود يطبع ال لسته زي ما هي 
print(x)

{1, 2, 3, 4, 5, 6, 8}
{3, 4, 5}
{1, 2, 3}
{6}
{1, 2}
{1, 2, 3, 4, 5, 7, 8, 9}
{1, 2, 3, 4, 5, 7, 8, 9, 10}


In [45]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
list(range(0,10,3))

[0, 3, 6, 9]

In [48]:
list(range(10,1,-3))

[10, 7, 4]

In [49]:
for i in range(5):
    if i==3 :
        continue
    print(i)

0
1
2
4


In [ ]:
print("welcome to multblication table")
x=int(input("Enter the number:"))
print("multiplication table for",x)
for r in range(11):
    s=x * r
    print( x,"*",  r,"=",s)
    #جدول ضرب

welcome to multblication table
multiplication table for 5
5 * 0 = 0
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [51]:
def retfun(salary):
    return salary+200
retfun(1000)
retfun(2000)
#هنا بتاخد اخر واحده return

2200

In [52]:
def x(salary):
    return salary+200
print(x(2000))
x(1000)

2200


1200

In [53]:
def sum(x,y):
    return x+y 
sum(9,6)

15

In [54]:
def radius(radius):
  print("the area is=",(3.14*radius**2))#هنا مش عاوزه تشتغل 
radius(3)

the area is= 28.26


In [56]:
import numpy as np
a=[1,2,3,4,5]
print('a=',a)#هنا لسته عاديه 
array1=np.array(a)
print('array1=',array1)#هنا عملتها كانها array هنا1

a= [1, 2, 3, 4, 5]
array1= [1 2 3 4 5]


In [2]:
import numpy as np
u=[[1,2,3] , [4,5,6],[7,8,9]]
u1=np.array(u)#هنا عملتها arrayبس 3
print(u1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
w=[[1,2,3] ,[4,5,6] ,[7,8,9]]
w1=np.array(w)
print(w1)
print(w1.shape)#shape هنا بتعمل بتشوف عندك كام صف ف كام عمود

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [4]:
a=2
a1=np.array(a)
print(a1)
print(a1.shape)#هنا عملت shape لرقم بس هيطلع كورس فاضي
#هنا حاجه اسمهاno D

2
()


In [5]:
R=[1,2,3,4,5,6]
R1=np.array(R)
print(R1[0] ,R1[2])#هنا index ف numpy array 
print(R[0], R[2])# هنا index ف lists
#معني الكلام ان index في الاتنين واحد مفيش اختلاف

1 3
1 3


In [61]:
r1=np.array([0.5,8,0.1,6,4,3,2])
print(type(r1[3]))
#هنا الخلاصه ان nump بتجعل كل القيم الا ف المصفوفه نفس النوع لو فيه عنصر عشري بتحول القيم كلها الي ارقام عشريه


<class 'numpy.float64'>


In [62]:
a=np.array([1,3,4,6,8,4])
a.dtype#dtype الفائده هنا بتشوف نوع المصفوفه كلها 


dtype('int64')

In [63]:
a=np.array([1,0.2,1,3,5,6])
a.dtype#بس لو المصفوفه فيها ارقام عشريه هيطلع كله ارقام عشريه

dtype('float64')

In [64]:
s=np.array(['E','W','A','123456789'])
s.dtype #output عندي u9 لان عندي اعلي اسم 9حروف 

dtype('<U9')

In [65]:
a=[1,3,4,56,67]
[a[1],a[0],a[3]]#هنا بنعمل كده بدل index ده ف numpy

[3, 1, 56]

In [66]:
a=np.array([[1,2,3],#عاوز 1و2و4و5
   [4,5,6],
   [7,8,9]])
a[0:2,:2]#هنا بقا nump array افضل من index ف لسته 

array([[1, 2],
       [4, 5]])

In [ ]:
a=np.array([[2,3,4],
            [7,43,21],
            [2234,567,876],
            [221,32,5443]])#المطلوب طباعه 3و4و43و21و567و876و32و5443
print(a)



[[   2    3    4]
 [   7   43   21]
 [2234  567  876]
 [ 221   32 5443]]


In [70]:
import numpy as np
a=np.array([[2,-4],[2.5,0.25]])
print(a)
b=np.array([2,2])
c=np.dot(a,b).reshape(2,1)
print(c)


[[ 2.   -4.  ]
 [ 2.5   0.25]]
[[-4. ]
 [ 5.5]]


In [69]:
print (2)
print (2+2)
print("ezzmohamedaliafify")
print() #هنا هيطبعلي السطر فاضي بس فيه سطر موجود
print("ezz \nmohamed \nali\nafify") #هنا مش هيسيب مسافه علشان انا حاطط الكلمه جنب \nع طول
print("ezz\n mohamed\n ali \n afify") #هنا هيسيب مسافه علشان انا سايب مسافه بين الكلمه وبين\n
print("ezz"+"mohamed") #هنا هيطبعلي ezzmohamed جنب بعض مفيش بينهم فاصل نحل المشكله ده ازاي 
#عندي 3طرق احل بيهم المشكله ده 
print("ezz "+"mohamed") #اول طريقه 
print("ezz"+" "+"mohamed") #تاني طريقه
print("ezz"+" mohamed") #تالت طريقه 
#عندي حاجه كمان عاوز اتكلم فيها مينفعشي اسيب مسافه قبل اي امر زي print

#او كويز ليه EXl
#صلح الاخطاء الا ف الكود ده
#print("hello"+ " "ibrahim")
# print("hello " + "ibrahim")
#print(hello" + " ibrahim")
#print("hello" + " " "ibrahim"
#prin("hello" + " " "ibrahim")
# الحل بتاعي
print("hello"+"ibrahim")
print("hello "+"ibrahim")
print("hello"+" ibrahim")
print("hello"+" "+"ibrahim")
print("hello"+" "+"ibrahim")
#الحل صح الحمد لله ميه ميه
input("what is your name? ")#هنا بنعمل امر input بنخلي الامر هوا الا يقولي دخل الاجابه 
#الاجابه هنا بتيقي جنب السؤال 
#لو عاوزين الاجتبه تحت السؤال مش جنبه اعمل اي نضيف امر \n كده يعني 
input("what is your name? \n")
#طب دلوقتي المعلومات الا انا عملتها ده راحت فين اتحفظت ولا لا عاوزين نشوف 
input("what is your name?")
print("hello"+ input("what is your name?"))
#كده انا عرفت انه سجل المعلومات ده عنده كده تمام اقوي علشان لو حبيت اعمل سؤال علي المعلومات ده بعد كده
#عارفين احنا لو عاوزين مسافه بين كلمة hello والمدخل الا هدخله نعمل اي تعالي نجرب 
input("what is your name?")
print("hello" +" "+ input("what is your name?"))
#كده عمل معانا مسافه بين الكلمتين

2
4
ezzmohamedaliafify

ezz 
mohamed 
ali
afify
ezz
 mohamed
 ali 
 afify
ezzmohamed
ezz mohamed
ezz mohamed
ezz mohamed
helloibrahim
hello ibrahim
hello ibrahim
hello ibrahim
hello ibrahim
helloezz
hello ezz


In [71]:
teams=['Real Madrid','Inter Milan','Bayern Munich','Paris Saint-Germain','Arsenal','Borussia Dortmund','Aston Villa'] #⚽⚽⚽
teams.insert(0,'Barcelona')
#print(teams)
#دور ربع النهائي 💥💥💥💥💥💥💥💥
# First Match (Real Madrid *** Arsenal) 
teams.pop(5)
#print(teams)
# Second Match (Paris Saint-Germain *** Aston Villa)
teams.remove('Aston Villa')
#print(teams)
# Third Match (Bayern Munich *** Inter Milan)
teams.pop(2)
#print(teams)
# Fourth Match (Barcelona *** Borussia Dortmund)
teams.remove('Borussia Dortmund')
#print(teams)
 #🔥🔥🔥🔥🔥🔥🔥دور نصف النهائي
# First Match (Real Madrid *** Paris Saint-Germain)💥💥💥💥💥💥💥
teams.pop(3)
#print(teams)
# Second Match (Barcelona *** Bayern Munich)💥💥💥💥💥💥💥
teams.pop(2)
#print(teams)
# Final Match 
#[ Barcelona ********** Real Madrid ]
print( "="*40)
teams.pop(1)
print(teams)
print( "="*40)
print("🏆✨ Congratulations to Barcelona ⚽🎉🎉🎉🎉💙💙💙💙💙 ✨🏆")
print("="*40 )

['Barcelona']
🏆✨ Congratulations to Barcelona ⚽🎉🎉🎉🎉💙💙💙💙💙 ✨🏆


pip\ conda 
is a package manger for python to install

shorthand if هنا ifجوه الامر

prime number 
عدد يقبل القسمه ع نفسه
عدد يقبل القسمه علي 1 
دول كده  عدد prime

not prime number
عكس الكلام الا فوق 

دالة Recursion
هي دالة بتنده على نفسها جوا الكود بتاعها.
يعني وانت شغال جوا الدالة، بتستدعي نفس الدالة تاني

In [46]:
#Write a Python function that takes a number as a parameter and check whether the number is prime or not
#with recursion
x=int(input('num='))
def prime(x):
    if x<=1:
        print ('prime')
    elif x % 2 == 0 :
        print('not prime')
    else:
        print('prime')
prime(x) 

prime


دالة out recursion
هي دالة ما بتناديش نفسها، يعني بتنفس شغلها مرة واحدة


In [ ]:
#Write a Python function that takes a number as a parameter and check whether the number is prime or not
#with out recursion
number = int(input("Enter a number: "))
if is_prime (number): 
    print("The number is prime")
else:
    print("The number is not prime")



The number is prime


دالة Recursion
هي دالة بتنده على نفسها جوا الكود بتاعها.
يعني وانت شغال جوا الدالة، بتستدعي نفس الدالة تاني

In [ ]:
#Write a Python function to calculate the factorial of a number (a non-negative integer).
#The function accepts the number as an argument
#using recursion
n=int(input('number'))
def factorial_recursive(n):
    if n <=0:
        return 1
    else:
        return n * factorial_recursive(n - 1)
factorial_recursive(n)

120

دالة out recursion
هي دالة ما بتناديش نفسها، يعني بتنفس شغلها مرة واحدة

In [124]:
#Write a Python function to calculate the factorial of a number (a non-negative integer).
#The function accepts the number as an argument
#using out recursion
n=int(input('number'))
def factorial_loop(n):
    if n<=0:
     return'number is negative'
    result= 1
    for i in range(2,n+1):
       result*=i
    return result 
factorial_loop(n)

120

In [ ]:
import RPi.GPIO as GPIO#هنا جبت المكتبه 
GPIO.setmode(GPIO.BCM) 
motor1_RPWM = 17
motor1_LPWM = 18
motor2_RPWM = 22
motor2_LPWM = 23
GPIO.setup(motor1_RPWM, GPIO.OUT)
GPIO.setup(motor1_LPWM, GPIO.OUT)
GPIO.setup(motor2_RPWM, GPIO.OUT)
GPIO.setup(motor2_LPWM, GPIO.OUT)
#دو الا مسولين عن البنات ترقيم البنات للمواتير 
def forward():
    GPIO.output(motor1_RPWM, GPIO.HIGH)
    GPIO.output(motor1_LPWM, GPIO.LOW)
    GPIO.output(motor2_RPWM, GPIO.HIGH)
    GPIO.output(motor2_LPWM, GPIO.LOW)

def backward():
    GPIO.output(motor1_RPWM, GPIO.LOW)
    GPIO.output(motor1_LPWM, GPIO.HIGH)
    GPIO.output(motor2_RPWM, GPIO.LOW)
    GPIO.output(motor2_LPWM, GPIO.HIGH)

def turn_right():
    GPIO.output(motor1_RPWM, GPIO.LOW)
    GPIO.output(motor1_LPWM, GPIO.HIGH)
    GPIO.output(motor2_RPWM, GPIO.HIGH)
    GPIO.output(motor2_LPWM, GPIO.LOW)

def turn_left():
    GPIO.output(motor1_RPWM, GPIO.HIGH)
    GPIO.output(motor1_LPWM, GPIO.LOW)
    GPIO.output(motor2_RPWM, GPIO.LOW)
    GPIO.output(motor2_LPWM, GPIO.HIGH)

def stop():
    GPIO.output(motor1_RPWM, GPIO.LOW)
    GPIO.output(motor1_LPWM, GPIO.LOW)
    GPIO.output(motor2_RPWM, GPIO.LOW)
    GPIO.output(motor2_LPWM, GPIO.LOW)







